version: "3"

services:
  alpine-sourcerercc:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      # uses the '.' if not given, so there is no hardcoding necessary
      - ${LINK_FROM:-.}/:/home/sourcerercc-user/data:rw
    environment:
      # has to be given, is the folder to source from
      CC_ARG: $SOURCERER_CC_INPUT
      # if non is given, we use the linked container
      MYSQL_HOST: ${MYSQL_HOST:-mysql-db-sourcerercc}
      # if none is given, it will be generated automatically
      PROJECTS_LIST: ${PROJECT_LIST:-}
    links:
      - mysql-db-sourcerercc
    depends_on:
      - mysql-db-sourcerercc
  mysql-db-sourcerercc:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'oopslaDB'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'p'
      MYSQL_ROOT_PASSWORD: 'p'
    ports:
      - 3306:3306
    expose:
      - 3306
    command:
      - "--max-allowed-packet=68157440"
